import express from "express";import cors from "cors";import dotenv from "dotenv";import bcrypt from "bcryptjs";import Database from "better-sqlite3";import nodemailer from "nodemailer";import jwt from "jsonwebtoken";import rateLimit from "express-rate-limit";import crypto from "crypto";
dotenv.config();const app=express(),db=new Database("trusty-pay.db"),PORT=+process.env.PORT||4000,SECRET=process.env.JWT_SECRET||"CHANGE_ME";app.use(cors());app.use(express.json());
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,mobile TEXT NOT NULL,password_hash TEXT NOT NULL,referral_id TEXT,email_verified INTEGER DEFAULT 0,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS otp_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL,otp_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER DEFAULT 0,created_at INTEGER NOT NULL);`);
const limit=rateLimit({windowMs:15*60*1000,limit:8});const email=x=>String(x||"").trim().toLowerCase();const hash=x=>crypto.createHash("sha256").update(x).digest("hex");const otp=()=>String(crypto.randomInt(100000,1000000));
function transport(){if(!process.env.SMTP_HOST)return null;return nodemailer.createTransport({host:process.env.SMTP_HOST,port:+process.env.SMTP_PORT||587,secure:String(process.env.SMTP_SECURE)==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}})}
async function mail(to,code){let t=transport();if(!t){if(process.env.DEV_LOG_OTP==="true"){console.log("DEV OTP",to,code);return}throw Error("SMTP email service is not configured.")}await t.sendMail({from:process.env.EMAIL_FROM,to,subject:"Your TRUSTY PAY verification code",text:`Your TRUSTY PAY verification code is ${code}. It expires in 5 minutes.`,html:`<div style="font-family:Arial"><h2>TRUSTY PAY</h2><p>Your verification code is:</p><h1>${code}</h1><p>Expires in 5 minutes.</p></div>`})}
app.get("/api/health",(_,r)=>r.json({ok:true}));
app.post("/api/auth/signup/request-otp",limit,async(q,r)=>{try{let {name,mobile,password,referralId}=q.body,e=email(q.body.email);if(!name||!mobile||!e||password?.length<8)return r.status(400).json({error:"Fill all fields; password must be 8+ characters."});let u=db.prepare("SELECT * FROM users WHERE email=?").get(e);let ph=await bcrypt.hash(password,12);if(u?.email_verified)return r.status(409).json({error:"Email already registered."});if(u)db.prepare("UPDATE users SET name=?,mobile=?,password_hash=?,referral_id=? WHERE email=?").run(name,mobile,ph,referralId||null,e);else db.prepare("INSERT INTO users(name,email,mobile,password_hash,referral_id,created_at) VALUES(?,?,?,?,?,?)").run(name,e,mobile,ph,referralId||null,new Date().toISOString());let code=otp();db.prepare("DELETE FROM otp_requests WHERE email=?").run(e);db.prepare("INSERT INTO otp_requests(email,otp_hash,expires_at,created_at) VALUES(?,?,?,?)").run(e,hash(code),Date.now()+300000,Date.now());await mail(e,code);r.json({ok:true,message:"OTP sent to your email."})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/auth/signup/verify-otp",limit,(q,r)=>{let e=email(q.body.email),code=String(q.body.otp||""),o=db.prepare("SELECT * FROM otp_requests WHERE email=? ORDER BY id DESC LIMIT 1").get(e);if(!o)return r.status(400).json({error:"No active OTP."});if(Date.now()>o.expires_at)return r.status(400).json({error:"OTP expired."});if(o.attempts>=5)return r.status(429).json({error:"Too many attempts."});db.prepare("UPDATE otp_requests SET attempts=attempts+1 WHERE id=?").run(o.id);if(hash(code)!==o.otp_hash)return r.status(400).json({error:"Incorrect OTP."});db.prepare("UPDATE users SET email_verified=1 WHERE email=?").run(e);db.prepare("DELETE FROM otp_requests WHERE email=?").run(e);let u=db.prepare("SELECT id,name,email,mobile,referral_id,created_at FROM users WHERE email=?").get(e),token=jwt.sign({userId:u.id,email:u.email},SECRET,{expiresIn:"7d"});r.json({ok:true,token,user:u})});
app.post("/api/auth/login",limit,async(q,r)=>{let e=email(q.body.email),u=db.prepare("SELECT * FROM users WHERE email=?").get(e);if(!u||!(await bcrypt.compare(q.body.password||"",u.password_hash)))return r.status(401).json({error:"Invalid email or password."});if(!u.email_verified)return r.status(403).json({error:"Verify your email first."});let token=jwt.sign({userId:u.id,email:u.email},SECRET,{expiresIn:"7d"});r.json({ok:true,token,user:{id:u.id,name:u.name,email:u.email,mobile:u.mobile,referralId:u.referral_id,createdAt:u.created_at}})});
app.listen(PORT,()=>console.log("TRUSTY PAY API on http://localhost:"+PORT));